routes/admin.php
<?php
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\LevelController;
// use App\Http\Controllers\Admin\PlanController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\AccountingController;
use App\Http\Controllers\Admin\InfoStudentController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\CreditController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\LessonController;
use App\Http\Controllers\Admin\SystemController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\Admin\InfoTeacherController;
use App\Http\Controllers\Admin\ScheduleTeacherController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\VedamoController;

//Rutas de administración sin disabled
Route::prefix('go-admin')->middleware(['auth','verified'])->group(function(){
	Route::get('suspend',[AdminController::class,'suspend'])->name('admin.suspend');
});

Route::prefix('go-admin')->middleware(['auth','verified','disabled','role:admin|teacher|student'])->group(function () {

	//Admin
	Route::get('/',[AdminController::class,'index'])->name('admin.index');
	Route::get('users/suspend/{id}',[UserController::class,'suspend'])->name('users.suspend');
	Route::get('users/roles/{type}',[UserController::class,'type'])->name('users.type');
	Route::post('users/featured',[UserController::class,'featured'])->name('users.featured');
	Route::resource('users',UserController::class);
	Route::resource('levels',LevelController::class);
	// Route::resource('plans',PlanController::class);
	Route::resource('testimonials',TestimonialController::class);
	Route::resource('slides',SlideController::class);

	//Info Student
	Route::resource('info_student',InfoStudentController::class);

	//Info Student
	Route::resource('systems',SystemController::class);

	//Credit
	Route::resource('credits',CreditController::class);

	//Products
	Route::resource('products',ProductController::class);

    //Posts
    Route::post('gallery/destroy',[PostController::class,'destroyGallery'])->name('destroy.gallery');
    Route::post('posts/gallery',[PostController::class,'gallery'])->name('upload.gallery');
    Route::resource('posts',PostController::class);

    //Categories
    Route::resource('categories',CategoryController::class);

	//Ingresos
	Route::get('accounting/income',[AccountingController::class,'income'])->name('accounting.income');
	Route::get('accounting/lesson',[AccountingController::class,'lesson'])->name('accounting.lesson');

	//Change lang
	Route::post('change/lang', [AdminController::class,'lang'])->name('lang.change');
});


Route::prefix('go-admin/manager')->middleware(['auth','verified','disabled'])->group(function () {
});

//Logout
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout.click');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require('teacher.php');
require('admin.php');
require('student.php');

//Rutas de Auth
Auth::routes(['register'=>false,'verify' => true]);

Route::get('/', function () {
    return view('welcome');
});


//Rutas para FrontEnd
Route::get('/teacher-register', [HomeController::class, 'teacher_register'])->name('register.teacher');
Route::get('/register', [HomeController::class, 'student_register'])->name('register.student');
Route::post('/save-teacher', [HomeController::class, 'teacher_save'])->name('save.teacher');
Route::post('/save-student', [HomeController::class, 'student_save'])->name('save.student');
Route::post('change_lang', [HomeController::class, 'change_lang'])->name('change.lang');
Route::post('search', [HomeController::class, 'search'])->name('search');

//page
Route::get('/', [HomeController::class, 'index'])->name('front.index');
Route::get('about', [HomeController::class, 'about'])->name('front.about');
Route::get('blog', [HomeController::class, 'post'])->name('front.post');
Route::get('teachers', [HomeController::class, 'teacher'])->name('front.teacher');
Route::get('philosophy', [HomeController::class, 'philosophy'])->name('front.philosophy');
Route::get('hiring', [HomeController::class, 'hiring'])->name('front.hiring');
Route::get('pricing', [HomeController::class, 'pricing'])->name('front.pricing');
Route::get('notice-of-privacy', [HomeController::class, 'privacy'])->name('front.privacy');
Route::get('terms-and-conditions', [HomeController::class, 'terms'])->name('front.terms');
Route::get('faqs', [HomeController::class, 'faqs'])->name('front.faqs');
Route::get('blog/search', [HomeController::class, 'search'])->name('front.search');
Route::get('blog/{category}/{url}', [HomeController::class, 'single'])->name('front.single');
Route::get('blog/{category}', [HomeController::class, 'category'])->name('front.category');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

//Invoices
// Route::get('/invoices', [StripeController::class,'invoices'])->name('invoices.stripe');
// Route::get('/invoice/{user_id}/{invoice_id}', [StripeController::class,'invoice'])->name('invoice.stripe');

//Get image
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path($filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('get.image');

resources/views/front/parts/footer.blade.php
<!--Cookies-->
 <a href="javascript:void(0)" class="js-lcc-settings-toggle"></a>
 
<footer style="background-image:url('{{asset('/assets/img/home/bg-header.jpg')}}');">
	<div class="container-fluid padding">
		<div class="row">
			<div class="col-xl-3 col-lg-4">
				<img src="{{route('get.image',$global_system->logo)}}" alt="Go Amigo" class="img-fluid logo">
			</div>
		</div>
		<div class="row">
			<div class="col-xl-3 col-lg-4">
				<h3>Quick links</h3>
				<ul>
					@php
			            $route = Route::current()->getName();
			          @endphp
			          <li class="{{($route == 'front.index')?'active':''}}">
			            <a href="{{route('front.index')}}">> {{__('navbar.menu.home')}}</a>
			          </li>
			          <li class="{{($route == 'front.about')?'active':''}}">
			            <a href="{{route('front.about')}}">> {{__('navbar.menu.about')}}</a>
			          </li>
			          <li class="{{($route == 'front.philosophy')?'active':''}}">
			            <a href="{{route('front.philosophy')}}">> {{__('navbar.menu.philosophy')}}</a>
			          </li>
			          <li class="{{($route == 'front.teacher')?'active':''}}">
			            <a href="{{route('front.teacher')}}">> {{__('navbar.menu.teachers')}}</a>
			          </li>
			          <li class="{{($route == 'front.pricing')?'active':''}}">
			            <a href="{{route('front.pricing')}}">> {{__('navbar.menu.pricing')}}</a>
			          </li>
			          <li class="{{($route == 'front.hiring')?'active':''}}">
			            <a href="{{route('front.hiring')}}">> {{__('navbar.menu.hiring')}}</a>
			          </li>
			          <li class="{{($route == 'front.blog')?'active':''}}" style="display: none;">
			            <a href="#">> {{__('navbar.menu.blog')}}</a>
			          </li>
				</ul>
			</div>
			<div class="col-xl-3 col-lg-4">
				<h3>Privacy Policies</h3>
				<ul>
					<li class="{{($route == 'front.privacy')?'active':''}}">
			            <a href="{{route('front.privacy')}}">> {{__('navbar.menu.privacy')}}</a>
			        </li>
				    <li class="{{($route == 'front.terms')?'active':''}}">
		                <a href="{{route('front.terms')}}">> {{__('navbar.menu.terms')}}</a>
		            </li>
		            <li class="{{($route == 'front.faqs')?'active':''}}">
		                <a href="{{route('front.faqs')}}">> Faqs</a>
		            </li>
				</ul>
			</div>
			<div class="col-xl-3 col-lg-4">
				<h3>Contact With US</h3>
				<ul class="social">
					@if ($global_system->facebook)
						<li>
							<a href="{{$global_system->facebook}}" target="_blank">
								<img src="{{asset('assets/img/facebook.png')}}" alt="Facebook">
							</a>
						</li>	
					@endif
					@if ($global_system->youtube)
						<li>
							<a href="{{$global_system->youtube}}" target="_blank">
								<img src="{{asset('assets/img/youtube.png')}}" alt="Youtube">
							</a>
						</li>
					@endif
					@if ($global_system->instagram)
						<li>
							<a href="{{$global_system->instagram}}" target="_blank">
								<img src="{{asset('assets/img/instagram.png')}}" alt="Instagram">
							</a>
						</li>
					@endif
				</ul>
				<div class="row m-b">
					<div class="col-lg-3">
						<img src="{{asset('assets/img/email.png')}}" alt="Email" class="img-fluid icon">
					</div>
					<div class="col-lg-9 p-l">
						@php
							$emails = explode(',',$global_system->emails);
						@endphp

						@foreach ($emails as $key => $email)
							@if ($key == 0 || $key == 1)
								<a href="mailto:{{$email}}">{{$email}}</a>	
							@endif
						@endforeach
					</div>
				</div>
			</div>
			<div class="col-xl-3 col-lg-4">
				<h3>Become a <span>Go Amigo teacher!</span></h3>
				<p>Manage your schedules, combine classes with your regular job, or even work remotely. Earn money and be part of a change in future generations.</p>
				<a href="{{route('front.hiring')}}" class="btn btn-green">Learn more</a>
			</div>
		</div>
	</div>
	<p class="copy">{{$global_system->copyright}}</p>
</footer>

resources/views/front/parts/navbar.blade.php
<div id="navbar">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-2 col-md-2 col-12">
        <a href="{{route('front.index')}}">
            <img src="{{route('get.image',$global_system->logo)}}" class="logo top">
        </a>
      </div>
      <div class="col-xl-6 col-md-2 col-1 sp">

        <ul class="top hidden-mobile">
          @php
            $route = Route::current()->getName();
          @endphp
          <li class="{{($route == 'front.index')?'active':''}}">
            <a href="{{route('front.index')}}">{{__('navbar.menu.home')}}</a>
          </li>
          <li class="{{($route == 'front.about')?'active':''}}">
            <a href="{{route('front.about')}}">{{__('navbar.menu.about')}}</a>
          </li>
          <li class="{{($route == 'front.philosophy')?'active':''}}">
            <a href="{{route('front.philosophy')}}">{{__('navbar.menu.philosophy')}}</a>
          </li>
          <li class="{{($route == 'front.teacher')?'active':''}}">
            <a href="{{route('front.teacher')}}">{{__('navbar.menu.teachers')}}</a>
          </li>
          <li class="{{($route == 'front.pricing')?'active':''}}">
            <a href="{{route('front.pricing')}}">{{__('navbar.menu.pricing')}}</a>
          </li>
          <li class="{{($route == 'front.hiring')?'active':''}}">
            <a href="{{route('front.hiring')}}">{{__('navbar.menu.hiring')}}</a>
          </li>
          <li class="{{($route == 'front.post')?'active':''}}">
            <a href="{{route('front.post')}}">{{__('navbar.menu.blog')}}</a>
          </li>
          <li class="close-burger">
            <a href="#">
              <i class="far fa-times-circle fa-2x"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-xl-3 col-md-7 col-7 text-right">

          @if (Auth::check())
            @if (auth()->user()->hasRole('admin'))
              <a href="{{route('admin.index')}}" class="btn btn-purple">{{__('navbar.menu.account')}}</a>
              <a href="{{route('logout.click')}}" class="btn btn-green">Cerrar sesión</a>
            @elseif(auth()->user()->hasRole('teacher'))
              <a href="{{route('admin.teacher.index')}}" class="btn btn-purple">{{__('navbar.menu.account')}}</a>
              <a href="{{route('logout.click')}}" class="btn btn-green">Cerrar sesión</a>
            @elseif(auth()->user()->hasRole('student'))
              <a href="{{route('admin.student.index')}}" class="btn btn-purple">{{__('navbar.menu.account')}}</a>
              <a href="{{route('logout.click')}}" class="btn btn-green">Cerrar sesión</a>
            @endif
          @else
            <a href="{{route('admin.index')}}" class="btn btn-green top">{{__('navbar.menu.login')}}</a>
          @endif
      </div>
      <div class="col-xl-1 col-md-1 col-1">
        <i class="fas fa-bars fa-3x menu-burger"></i>
      </div>
    </div>
  </div>
</div>