routes/admin.php
<?php
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\LevelController;
// use App\Http\Controllers\Admin\PlanController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\AccountingController;
use App\Http\Controllers\Admin\InfoStudentController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\CreditController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\LessonController;
use App\Http\Controllers\Admin\SystemController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\Admin\InfoTeacherController;
use App\Http\Controllers\Admin\ScheduleTeacherController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\VedamoController;

//Rutas de administración sin disabled
Route::prefix('go-admin')->middleware(['auth','verified'])->group(function(){
	Route::get('suspend',[AdminController::class,'suspend'])->name('admin.suspend');
});

Route::prefix('go-admin')->middleware(['auth','verified','disabled','role:admin|teacher|student'])->group(function () {

	//Admin
	Route::get('/',[AdminController::class,'index'])->name('admin.index');
	Route::get('users/suspend/{id}',[UserController::class,'suspend'])->name('users.suspend');
	Route::get('users/roles/{type}',[UserController::class,'type'])->name('users.type');
	Route::post('users/featured',[UserController::class,'featured'])->name('users.featured');
	Route::resource('users',UserController::class);
	Route::resource('levels',LevelController::class);
	// Route::resource('plans',PlanController::class);
	Route::resource('testimonials',TestimonialController::class);
	Route::resource('slides',SlideController::class);

	//Info Student
	Route::resource('info_student',InfoStudentController::class);

	//Info Student
	Route::resource('systems',SystemController::class);

	//Credit
	Route::resource('credits',CreditController::class);

	//Products
	Route::resource('products',ProductController::class);

    //Posts
    Route::post('gallery/destroy',[PostController::class,'destroyGallery'])->name('destroy.gallery');
    Route::post('posts/gallery',[PostController::class,'gallery'])->name('upload.gallery');
    Route::resource('posts',PostController::class);

    //Categories
    Route::resource('categories',CategoryController::class);

	//Ingresos
	Route::get('accounting/income',[AccountingController::class,'income'])->name('accounting.income');
	Route::get('accounting/lesson',[AccountingController::class,'lesson'])->name('accounting.lesson');

	//Change lang
	Route::post('change/lang', [AdminController::class,'lang'])->name('lang.change');
});


Route::prefix('go-admin/manager')->middleware(['auth','verified','disabled'])->group(function () {
});

//Logout
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout.click');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require('teacher.php');
require('admin.php');
require('student.php');

//Rutas de Auth
Auth::routes(['register'=>false,'verify' => true]);

Route::get('/', function () {
    return view('welcome');
});


//Rutas para FrontEnd
Route::get('/teacher-register', [HomeController::class, 'teacher_register'])->name('register.teacher');
Route::get('/register', [HomeController::class, 'student_register'])->name('register.student');
Route::post('/save-teacher', [HomeController::class, 'teacher_save'])->name('save.teacher');
Route::post('/save-student', [HomeController::class, 'student_save'])->name('save.student');
Route::post('change_lang', [HomeController::class, 'change_lang'])->name('change.lang');
Route::post('search', [HomeController::class, 'search'])->name('search');

//page
Route::get('/', [HomeController::class, 'index'])->name('front.index');
Route::get('about', [HomeController::class, 'about'])->name('front.about');
Route::get('blog', [HomeController::class, 'post'])->name('front.post');
Route::get('teachers', [HomeController::class, 'teacher'])->name('front.teacher');
Route::get('philosophy', [HomeController::class, 'philosophy'])->name('front.philosophy');
Route::get('hiring', [HomeController::class, 'hiring'])->name('front.hiring');
Route::get('pricing', [HomeController::class, 'pricing'])->name('front.pricing');
Route::get('notice-of-privacy', [HomeController::class, 'privacy'])->name('front.privacy');
Route::get('terms-and-conditions', [HomeController::class, 'terms'])->name('front.terms');
Route::get('faqs', [HomeController::class, 'faqs'])->name('front.faqs');
Route::get('blog/search', [HomeController::class, 'search'])->name('front.search');
Route::get('blog/{category}/{url}', [HomeController::class, 'single'])->name('front.single');
Route::get('blog/{category}', [HomeController::class, 'category'])->name('front.category');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

//Invoices
// Route::get('/invoices', [StripeController::class,'invoices'])->name('invoices.stripe');
// Route::get('/invoice/{user_id}/{invoice_id}', [StripeController::class,'invoice'])->name('invoice.stripe');

//Get image
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path($filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('get.image');

app/Models/Level.php
<?php

namespace App\Models;

use App\Models\Plan;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Level extends Model
{
    use HasFactory, SoftDeletes, HasTranslations;

    protected $guarded = [];

    //Translatable
    public $translatable = ['name','description'];
}

app/Http/Controllers/Admin/LevelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Level;
use App\Http\Requests\StoreLevelRequest;
use Auth;

class LevelController extends Controller
{
    public function __construct(){
        $this->middleware(['role:admin']);
    }
    
    public function index()
    {
        $data = [
            'levels' => Level::select('id','name','description','lessons')->latest()->get()
        ];

        return view('admin.levels.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.levels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreLevelRequest $request)
    {
        $level = Level::create($request->except('_token'));
        $level->save();

        return redirect()->route('levels.index')->with('success','Se agrego el nivel.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'level' => level::find($id)
        ];

        return view('admin.levels.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Get level
        $level = Level::find($id);

        //Get Lang
        $level->setTranslation('name',Auth::user()->language,$request->name)->save();
        $level->setTranslation('description',Auth::user()->language,$request->description)->save();
        $level->lessons = $request->lessons;
        $level->save();

        return redirect()->route('levels.index')->with('success','Se ha actualizado la información del nivel.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $level = Level::find($id);
        $level->delete();

        return redirect()->route('levels.index')->with('success','Se ha borrado el nivel.');
    }
}

resources/views/admin/levels/create.blade.php
@extends('layouts.admin')

@section('title')
	{{__('level.create.title')}}
@endsection

@push('css')
@endpush

@section('content')

	<div class="row">
		<div class="col-xl-12">
			<div class="card">
		        <div class="card-body">

		        	@if ($errors->any())
					    <div class="col-md-12">
					        <div class="alert alert-danger">
					            <ul>
					                @foreach ($errors->all() as $error)
					                    <li>{{ $error }}</li>
					                @endforeach
					            </ul>
					        </div>
					    </div>
					@endif
		            
		            <form action="{{route('levels.store')}}" method="post">
        				@csrf
			            <div class="row">
			            	<div class="col-12">
			            		<h3><strong>{{__('level.create.subtitle')}}</strong></h3><hr>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>{{__('level.create.name')}}</label>
			            			<input type="text" name="name" class="form-control {{($errors->first('name'))? 'invalid':''}}" value="{{old('name')}}" required>
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>{{__('level.create.description')}}</label>
			            			<textarea name="description" class="form-control {{($errors->first('description'))? 'invalid':''}}" value="{{old('description')}}"></textarea>
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>{{__('level.create.lesson')}}</label>
			            			<input type="number" name="lessons" class="form-control {{($errors->first('lessons'))? 'invalid':''}}" value="{{old('lessons')}}" required>
			            		</div>
			            	</div>
			            </div>
			            <div class="row">
				            <div class="col-xl-12">
				            	<a href="{{route('levels.index')}}" class="btn btn-danger">{{__('level.create.cancel')}}</a>
			            		<button type="submit" class="btn btn-success">{{__('level.create.add')}}</button>
			            	</div>
		            	</div>
		            </form>

		        </div>
		    </div>
	    </div>
    </div>

@endsection

@push('js')
@endpush

resources/views/admin/levels/edit.blade.php
@extends('layouts.admin')

@section('title','Editar nivel')

@push('css')
	
@endpush

@section('content')

	<div class="row">
		<div class="col-xl-12">
			@if (Session::has('success'))
			    <div class="alert alert-success">
			        {!! Session::get('success') !!}
			    </div>
			@endif
			<div class="card">
		        <div class="card-body">		            
		            <form action="{{route('levels.update',$data['level']->id)}}" method="post">
		            	@csrf
		            	{{ method_field('PATCH') }}
			            <div class="row">
			            	<div class="col-12">
			            		<h3><strong>Información</strong></h3><hr>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>Nombre</label>
			            			<input type="text" name="name" class="form-control" value="{{$data['level']->name}}" required>
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>Descripción</label>
			            			<textarea name="description" class="form-control">{{$data['level']->description}}</textarea>
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>No. de clases</label>
			            			<input type="number" name="lessons" class="form-control" value="{{$data['level']->lessons}}" required>
			            		</div>
			            	</div>
			            </div>
			            <div class="row">
				            <div class="col-xl-12">
				            	<a href="{{route('levels.index')}}" class="btn btn-danger">Salir sin guardar</a>
			            		<button type="submit" class="btn btn-success">Guardar cambios</button>
			            	</div>
		            	</div>
		            </form>

		        </div>
		    </div>
	    </div>
    </div>

@endsection

@push('js')
	<script src="{{asset('admin/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('admin/dist/js/pages/datatable/datatable-basic.init.js')}}"></script>
@endpush

resources/views/admin/levels/index.blade.php
@extends('layouts.admin')

@section('title')
	{{__('level.title')}}
@endsection

@section('subtitle')
@endsection

@push('css')
	<link href="{{asset('admin/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
	<link rel="stylesheet" href="{{asset('script/sweet/sweetalert2.min.css')}}">
	<link rel="stylesheet" href="{{asset('script/fancybox/jquery.fancybox.min.css')}}">
@endpush

@section('content')

	<div class="row">
		<div class="col-xl-12">

			@if (Session::has('success'))
			    <div class="alert alert-success">
			        {!! Session::get('success') !!}
			    </div>
			@endif

			<div class="card">
		        <div class="card-body">

		            <h4 class="card-title">{{__('level.all')}}</h4>
		            <div class="table-responsive">
                        <table id="multi_col_order" class="table table-striped table-bordered display no-wrap table-sm" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>{{__('level.table.name')}}</th>
                                    <th>{{__('level.table.description')}}</th>
                                    <th>{{__('level.table.lesson')}}</th>
                                    <th width="1em">{{__('level.table.action')}}</th>
                                </tr>
                            </thead>
                            <tbody>

                            	@foreach ($data['levels'] as $level)
                            		<tr>
	                                    <td>{{$level->id}}</td>
	                                    <td>{{$level->name}}</td>
	                                    <td>{{$level->description}}</td>
	                                    <td>{{$level->lessons}}</td>
	                                    <td>
	                                    	<a href="{{route('levels.edit',$level->id)}}" class="btn btn-sm btn-info">{{__('general.edit')}}</a>
	                                    	<a href="#" class="btn btn-sm btn-danger delete" data-id="{{$level->id}}">{{__('general.delete')}}</a>
	                                    	<form action="{{route('levels.destroy',$level->id)}}" method="post" style="display: inline-block;" id="delete-{{$level->id}}">
	                                    		@csrf
	                                    		@method('DELETE')
	                                    	</form>
	                                    </td>
	                                </tr>	
                            	@endforeach

                            </tbody>
                        </table>
                    </div>

                    <a href="{{route('levels.create')}}" class="btn btn-info">{{__('level.add')}}</a>

		        </div>
		    </div>
	    </div>
    </div>

@endsection

@push('js')
	<script src="{{asset('script/fancybox/jquery.fancybox.min.js')}}"></script>
	<script src="{{asset('admin/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('admin/dist/js/pages/datatable/datatable-basic.init.js')}}"></script>
    <script src="{{asset('script/sweet/sweetalert2.min.js')}}"></script>
    <script>
    	//Cerrar modal
    	$('#close-modal').click(function(){
		  $.fancybox.close();
		});

		//Preguntar si desea borrar
		$('.delete').on('click', function(e){

			e.preventDefault();
			var id = $(this).data('id');

			Swal.fire({
			  title: '¿Estas seguro?',
			  text: "Esta a apunto de eliminar el nivel.",
			  icon: 'warning',
			  showCancelButton: true,
			  confirmButtonColor: '#3085d6',
			  cancelButtonColor: '#d33',
			  cancelButtonText: 'Cancelar',
			  confirmButtonText: '¡Si, eliminar!'
			}).then((result) => {
			  if (result.isConfirmed) {
			  	$('#delete-'+id).submit();
			  }
			})

		});
		
    </script>	
@endpush