routes/admin.php
<?php
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\LevelController;
// use App\Http\Controllers\Admin\PlanController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\AccountingController;
use App\Http\Controllers\Admin\InfoStudentController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\CreditController;
use App\Http\Controllers\Admin\StudentController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\LessonController;
use App\Http\Controllers\Admin\SystemController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\Admin\InfoTeacherController;
use App\Http\Controllers\Admin\ScheduleTeacherController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\VedamoController;

//Rutas de administración sin disabled
Route::prefix('go-admin')->middleware(['auth','verified'])->group(function(){
	Route::get('suspend',[AdminController::class,'suspend'])->name('admin.suspend');
});

Route::prefix('go-admin')->middleware(['auth','verified','disabled','role:admin|teacher|student'])->group(function () {

	//Admin
	Route::get('/',[AdminController::class,'index'])->name('admin.index');
	Route::get('users/suspend/{id}',[UserController::class,'suspend'])->name('users.suspend');
	Route::get('users/roles/{type}',[UserController::class,'type'])->name('users.type');
	Route::post('users/featured',[UserController::class,'featured'])->name('users.featured');
	Route::resource('users',UserController::class);
	Route::resource('levels',LevelController::class);
	// Route::resource('plans',PlanController::class);
	Route::resource('testimonials',TestimonialController::class);
	Route::resource('slides',SlideController::class);

	//Info Student
	Route::resource('info_student',InfoStudentController::class);

	//Info Student
	Route::resource('systems',SystemController::class);

	//Credit
	Route::resource('credits',CreditController::class);

	//Products
	Route::resource('products',ProductController::class);

    //Posts
    Route::post('gallery/destroy',[PostController::class,'destroyGallery'])->name('destroy.gallery');
    Route::post('posts/gallery',[PostController::class,'gallery'])->name('upload.gallery');
    Route::resource('posts',PostController::class);

    //Categories
    Route::resource('categories',CategoryController::class);

	//Ingresos
	Route::get('accounting/income',[AccountingController::class,'income'])->name('accounting.income');
	Route::get('accounting/lesson',[AccountingController::class,'lesson'])->name('accounting.lesson');

	//Change lang
	Route::post('change/lang', [AdminController::class,'lang'])->name('lang.change');
});


Route::prefix('go-admin/manager')->middleware(['auth','verified','disabled'])->group(function () {
});

//Logout
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout.click');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require('teacher.php');
require('admin.php');
require('student.php');

//Rutas de Auth
Auth::routes(['register'=>false,'verify' => true]);

Route::get('/', function () {
    return view('welcome');
});


//Rutas para FrontEnd
Route::get('/teacher-register', [HomeController::class, 'teacher_register'])->name('register.teacher');
Route::get('/register', [HomeController::class, 'student_register'])->name('register.student');
Route::post('/save-teacher', [HomeController::class, 'teacher_save'])->name('save.teacher');
Route::post('/save-student', [HomeController::class, 'student_save'])->name('save.student');
Route::post('change_lang', [HomeController::class, 'change_lang'])->name('change.lang');
Route::post('search', [HomeController::class, 'search'])->name('search');

//page
Route::get('/', [HomeController::class, 'index'])->name('front.index');
Route::get('about', [HomeController::class, 'about'])->name('front.about');
Route::get('blog', [HomeController::class, 'post'])->name('front.post');
Route::get('teachers', [HomeController::class, 'teacher'])->name('front.teacher');
Route::get('philosophy', [HomeController::class, 'philosophy'])->name('front.philosophy');
Route::get('hiring', [HomeController::class, 'hiring'])->name('front.hiring');
Route::get('pricing', [HomeController::class, 'pricing'])->name('front.pricing');
Route::get('notice-of-privacy', [HomeController::class, 'privacy'])->name('front.privacy');
Route::get('terms-and-conditions', [HomeController::class, 'terms'])->name('front.terms');
Route::get('faqs', [HomeController::class, 'faqs'])->name('front.faqs');
Route::get('blog/search', [HomeController::class, 'search'])->name('front.search');
Route::get('blog/{category}/{url}', [HomeController::class, 'single'])->name('front.single');
Route::get('blog/{category}', [HomeController::class, 'category'])->name('front.category');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

//Invoices
// Route::get('/invoices', [StripeController::class,'invoices'])->name('invoices.stripe');
// Route::get('/invoice/{user_id}/{invoice_id}', [StripeController::class,'invoice'])->name('invoice.stripe');

//Get image
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path($filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('get.image');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;
use App\Models\System;

class Product extends Model
{
    use HasFactory, HasTranslations;

    protected $guarded = [];

    //Translatable
    public $translatable = ['name','description'];


    public function getGainAttribute()
    {
    	$system = System::find(1);

    	$paymentProfesor = $this->credits * $system->paymentfull;
    	$total = $this->price - $paymentProfesor;
    	
    	return '<span class="badge badge-success">&uarr;'.$total.' USD</span>';

    }
}

app/Http/Controllers/Admin/AccountingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\InvoiceTeacher;
use App\Models\InvoiceProduct;
use App\Models\Invoice;
use Carbon\Carbon;

class AccountingController extends Controller
{
    public function income()
    {
    	$data = [
    		// 'invoices' => InvoiceProduct::whereBetween('created_at',[Carbon::now()->startOfMonth(),Carbon::now()->endOfMonth()])->latest()->get(),
            'invoices' => InvoiceProduct::latest()->get(),
    	];

    	return view('admin.accounting.income', compact('data'));
    }

    public function lesson()
    {
         $data = [
            'invoices' => Invoice::latest()->get()
        ];

        return view('admin.accounting.lesson',compact('data'));
    }
}

resources/views/admin/accounting/create.blade.php
@extends('layouts.admin')

@section('title')
	{{__('slide.create.title')}}
@endsection

@push('css')
@endpush

@section('content')

	<div class="row">
		<div class="col-xl-12">
			<div class="card">
		        <div class="card-body">

		        	@if ($errors->any())
					    <div class="col-md-12">
					        <div class="alert alert-danger">
					            <ul>
					                @foreach ($errors->all() as $error)
					                    <li>{{ $error }}</li>
					                @endforeach
					            </ul>
					        </div>
					    </div>
					@endif
		            
		            <form action="{{route('slides.store')}}" method="post" enctype="multipart/form-data">
        				@csrf
			            <div class="row">
			            	<div class="col-12">
			            		<h3><strong>{{__('slide.create.subtitle')}}</strong></h3><hr>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>{{__('slide.create.name')}}</label>
			            			<input type="text" name="title" class="form-control {{($errors->first('title'))? 'invalid':''}}" value="{{old('title')}}" required>
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>{{__('slide.create.description')}}</label>
			            			<textarea name="description" class="form-control {{($errors->first('description'))? 'invalid':''}}" value="{{old('description')}}"></textarea>
			            		</div>
			            	</div>
			            	<div class="col-xl-6">
			            		<div class="form-group">
			            			<label>{{__('slide.create.button')}}</label>
			            			<input type="text" name="button" class="form-control {{($errors->first('button'))? 'invalid':''}}" value="{{old('button')}}">
			            		</div>
			            	</div>
			            	<div class="col-xl-6">
			            		<div class="form-group">
			            			<label>Url</label>
			            			<input type="text" name="url" class="form-control {{($errors->first('url'))? 'invalid':''}}" value="{{old('url')}}">
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>{{__('slide.create.image')}}</label>
			            			<input type="file" name="image" class="form-control" required>
			            		</div>
			            	</div>
			            </div>
			            <div class="row">
				            <div class="col-xl-12">
				            	<a href="{{route('slides.index')}}" class="btn btn-danger">{{__('slide.create.cancel')}}</a>
			            		<button type="submit" class="btn btn-success">{{__('slide.create.add')}}</button>
			            	</div>
		            	</div>
		            </form>

		        </div>
		    </div>
	    </div>
    </div>

@endsection

@push('js')
@endpush

resources/views/admin/accounting/edit.blade.php
@extends('layouts.admin')

@section('title','Editar sistema')

@push('css')
@endpush

@section('content')

	<div class="row">
		<div class="col-xl-6">
			@if (Session::has('success'))
			    <div class="alert alert-success">
			        {!! Session::get('success') !!}
			    </div>
			@endif
			<div class="card">
				<form action="{{route('systems.update',$system->id)}}" method="post" enctype="multipart/form-data">
				<div class="card-body">
					<div class="row">
						<div class="col-12">
		            		<h3><strong>Pago a profesores</strong></h3><hr>
		            	</div>
		            	<div class="col-xl-12">
		            		<div class="form-group">
		            			<label>Pago x clase pagada:</label>
		            			<input type="text" class="form-control" name="paymentfull" value="{{$system->paymentfull}}">
		            		</div>
		            	</div>
		            	<div class="col-xl-12">
		            		<div class="form-group">
		            			<label>Pago x clase penalizada:</label>
		            			<input type="text" class="form-control" name="paymenthalf" value="{{$system->paymenthalf}}">
		            		</div>
		            		<small>Recuerda que este ajuste se hace de manera inmediata inclusive a los pagos que estan por hacerse anteriores.</small>
		            	</div>
					</div>
				</div>
			</div>
			<div class="card">
		        <div class="card-body">
		            	@csrf
		            	{{ method_field('PATCH') }}
			            <div class="row">
			            	<div class="col-12">
			            		<h3><strong>Sistema</strong></h3><hr>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>Logo:</label>
			            			<input type="file" name="logo" class="form-control">
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>Nombre:</label>
			            			<input type="text" name="name" class="form-control" value="{{$system->name}}">
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<h3>Redes sociales</h3>
			            		<div class="form-group">
			            			<label>Facebook:</label>
			            			<input type="text" name="facebook" class="form-control" value="{{$system->facebook}}">
			            		</div>
			            		<div class="form-group">
			            			<label>Youtube:</label>
			            			<input type="text" name="youtube" class="form-control" value="{{$system->youtube}}">
			            		</div>
			            		<div class="form-group">
			            			<label>Instagram:</label>
			            			<input type="text" name="instagram" class="form-control" value="{{$system->instagram}}">
			            		</div>
			            	</div>
		            	
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>Correos de sistema: </label>
			            			<input type="text" name="emails" class="form-control" value="{{$system->emails}}" required>
			            			<small>Si desea agregar más de un correo, utilice coma para separar.</small>
			            		</div>
			            	</div>
			            	<div class="col-xl-12">
			            		<div class="form-group">
			            			<label>Copyright:</label>
			            			<input type="text" name="copyright" class="form-control" value="{{$system->copyright}}">
			            		</div>
			            	</div>
			            </div>
			            <div class="row">
				            <div class="col-xl-12">
				            	<a href="{{route('systems.index')}}" class="btn btn-danger">Salir sin guardar</a>
			            		<button type="submit" class="btn btn-success">Guardar cambios</button>
			            	</div>
		            	</div>
		            </form>
		        </div>
		    </div>
	    </div>
    </div>

@endsection

@push('js')
@endpush

resources/views/admin/accounting/income.blade.php
@extends('layouts.admin')

@section('title')
	Paquetes
@endsection

@section('subtitle')
@endsection

@push('css')
	<link href="{{asset('admin/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
	<link rel="stylesheet" href="{{asset('script/sweet/sweetalert2.min.css')}}">
	<link rel="stylesheet" href="{{asset('script/fancybox/jquery.fancybox.min.css')}}">
@endpush

@section('content')

	<div class="row">
		<div class="col-xl-12">

			<div class="card-group">
				 <div class="card border-right">
		            <div class="card-body">
		                <div class="d-flex d-lg-flex d-md-block align-items-center">
		                    <div>
		                        <div class="d-inline-flex align-items-center">
		                            <h2 class="text-dark mb-1 font-weight-medium"></h2>
		                        </div>
		                        <h6 class="text-muted font-weight-normal mb-0 w-100 text-truncate">Ingreso bruto</h6>
		                    </div>
		                    <div class="ml-auto mt-md-3 mt-lg-0">
		                        <span class="opacity-7 text-muted"><i data-feather="book-open"></i></span>
		                    </div>
		                </div>
		            </div>
		        </div>
		        <div class="card border-right">
		            <div class="card-body">
		                <div class="d-flex d-lg-flex d-md-block align-items-center">
		                    <div>
		                        <div class="d-inline-flex align-items-center">
		                            <h2 class="text-dark mb-1 font-weight-medium"></h2>
		                        </div>
		                        <h6 class="text-muted font-weight-normal mb-0 w-100 text-truncate">Ganancia mensual</h6>
		                    </div>
		                    <div class="ml-auto mt-md-3 mt-lg-0">
		                        <span class="opacity-7 text-muted"><i data-feather="book-open"></i></span>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>

			<div class="card">
		        <div class="card-body">

		            <h4 class="card-title">Últimas ingresos</h4>
		            <div class="table-responsive">
                        <table id="multi_col_order" class="table table-striped table-bordered display no-wrap table-sm" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Estudiante</th>
                                    <th>Producto</th>
                                    <th>Créditos</th>
                                    <th>Vigencia</th>
                                    <th>Costo</th>
                                    <th>Ganancia</th>
                                    <th>Fecha de compra</th>
                                </tr>
                            </thead>
                            <tbody>

                            	@foreach ($data['invoices'] as $invoice)
                            		<tr>
	                                    <td>{{$invoice->id}}</td>
	                                    <td>{{$invoice->user->name}} {{$invoice->user->last_name}}</td>
                                        <td>{{$invoice->product->name}}</td>
                                        <td>{{$invoice->product->credits}}</td>
                                        <td>{{$invoice->product->days}}</td>
                                        <td>{{$invoice->product->price}} USD</td>
                                        <td>{!!$invoice->product->gain!!}</td>
                                        <td>{{$invoice->created_at}}</td>
	                                </tr>	
                            	@endforeach

                            </tbody>
                        </table>
                    </div>

		        </div>
		    </div>
	    </div>
    </div>

@endsection

@push('js')
	<script src="{{asset('script/fancybox/jquery.fancybox.min.js')}}"></script>
	<script src="{{asset('admin/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('admin/dist/js/pages/datatable/datatable-basic.init.js')}}"></script>
    <script src="{{asset('script/sweet/sweetalert2.min.js')}}"></script>
    <script>
    	//Cerrar modal
    	$('#close-modal').click(function(){
		  $.fancybox.close();
		});

		//Preguntar si desea borrar
		$('.delete').on('click', function(e){

			e.preventDefault();
			var id = $(this).data('id');

			Swal.fire({
			  title: '¿Estas seguro?',
			  text: "Esta a apunto de eliminar el rotador.",
			  icon: 'warning',
			  showCancelButton: true,
			  confirmButtonColor: '#3085d6',
			  cancelButtonColor: '#d33',
			  cancelButtonText: 'Cancelar',
			  confirmButtonText: '¡Si, eliminar!'
			}).then((result) => {
			  if (result.isConfirmed) {
			  	$('#delete-'+id).submit();
			  }
			})

		});
		
    </script>	
@endpush

resources/views/admin/accounting/lesson.blade.php
@extends('layouts.admin')

@section('title')
	Clases
@endsection

@section('subtitle')
@endsection

@push('css')
	<link href="{{asset('admin/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
	<link rel="stylesheet" href="{{asset('script/sweet/sweetalert2.min.css')}}">
	<link rel="stylesheet" href="{{asset('script/fancybox/jquery.fancybox.min.css')}}">
@endpush

@section('content')

	<div class="row">
		<div class="col-xl-12">

			<div class="card-group">
				 <div class="card border-right">
		            <div class="card-body">
		                <div class="d-flex d-lg-flex d-md-block align-items-center">
		                    <div>
		                        <div class="d-inline-flex align-items-center">
		                            <h2 class="text-dark mb-1 font-weight-medium"></h2>
		                        </div>
		                        <h6 class="text-muted font-weight-normal mb-0 w-100 text-truncate">Ingreso bruto</h6>
		                    </div>
		                    <div class="ml-auto mt-md-3 mt-lg-0">
		                        <span class="opacity-7 text-muted"><i data-feather="book-open"></i></span>
		                    </div>
		                </div>
		            </div>
		        </div>
		        <div class="card border-right">
		            <div class="card-body">
		                <div class="d-flex d-lg-flex d-md-block align-items-center">
		                    <div>
		                        <div class="d-inline-flex align-items-center">
		                            <h2 class="text-dark mb-1 font-weight-medium"></h2>
		                        </div>
		                        <h6 class="text-muted font-weight-normal mb-0 w-100 text-truncate">Ganancia mensual</h6>
		                    </div>
		                    <div class="ml-auto mt-md-3 mt-lg-0">
		                        <span class="opacity-7 text-muted"><i data-feather="book-open"></i></span>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>

			<div class="card">
		        <div class="card-body">

		            <h4 class="card-title">Últimas ingresos</h4>
		            <div class="table-responsive">
                        <table id="multi_col_order" class="table table-striped table-bordered display no-wrap table-sm" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Estudiante</th>
                                    <th>Producto</th>
                                    <th>Créditos</th>
                                    <th>Vigencia</th>
                                    <th>Costo</th>
                                    <th>Ganancia</th>
                                    <th>Fecha de compra</th>
                                </tr>
                            </thead>
                            <tbody>

								@if($data['invoices']->count() > 1)
									@foreach ($data['invoices'] as $invoice)
										<tr>
											<td>{{$invoice->id}}</td>
											<td>{{$invoice->user->name}} {{$invoice->user->last_name}}</td>
											<td>{{$invoice->product->name}}</td>
											<td>{{$invoice->product->credits}}</td>
											<td>{{$invoice->product->days}}</td>
											<td>{{$invoice->product->price}} USD</td>
											<td>{!!$invoice->product->gain!!}</td>
											<td>{{$invoice->created_at}}</td>
										</tr>	
									@endforeach
								@endif
								
                            </tbody>
                        </table>
                    </div>

		        </div>
		    </div>
	    </div>
    </div>

@endsection

@push('js')
	<script src="{{asset('script/fancybox/jquery.fancybox.min.js')}}"></script>
	<script src="{{asset('admin/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('admin/dist/js/pages/datatable/datatable-basic.init.js')}}"></script>
    <script src="{{asset('script/sweet/sweetalert2.min.js')}}"></script>
    <script>
    	//Cerrar modal
    	$('#close-modal').click(function(){
		  $.fancybox.close();
		});

		//Preguntar si desea borrar
		$('.delete').on('click', function(e){

			e.preventDefault();
			var id = $(this).data('id');

			Swal.fire({
			  title: '¿Estas seguro?',
			  text: "Esta a apunto de eliminar el rotador.",
			  icon: 'warning',
			  showCancelButton: true,
			  confirmButtonColor: '#3085d6',
			  cancelButtonColor: '#d33',
			  cancelButtonText: 'Cancelar',
			  confirmButtonText: '¡Si, eliminar!'
			}).then((result) => {
			  if (result.isConfirmed) {
			  	$('#delete-'+id).submit();
			  }
			})

		});
		
    </script>	
@endpush